dpc-sdp/tide_landing_page

- config/install/field.storage.node.field_landing_page_c_primary.yml
- config/install/field.storage.node.field_landing_page_c_secondary.yml
JIRA:
- https://digital-engagement.atlassian.net/projects/SDPA/issues/SDPA-740
**Note:** there is a related PR in the `content-vic-gov-au` repos here: https://github.com/dpc-sdp/content-vic-gov-au/pull/234
**Screenshots:**
> [SDPA-740] Changed Primary Campaign and Secondary campaign fields.

- config/install/field.field.paragraph.card_event.field_paragraph_location.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-895
1. This is the changes applied for the `tide_landing_page` module 
1.  Fixed issue with location text display due to missing field configuration.
**Backend location fields:**
**Front location show correct text:**
> [SDPA-895] Fixed issue with card event location display.

- config/install/core.entity_form_display.paragraph.call_to_action.default.yml
- config/install/core.entity_view_display.paragraph.call_to_action.default.yml
- config/install/field.field.paragraph.call_to_action.field_paragraph_cta_style.yml
- config/install/field.storage.paragraph.field_paragraph_cta_style.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--call_to_action.yml
- tide_landing_page.info.yml
- tide_landing_page.install
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-790
> [SDPA-790] Added Style field for CTA paragraph.

- composer.json
- config/install/block_content.type.media_gallery.yml
- config/install/core.entity_form_display.block_content.media_gallery.default.yml
- config/install/core.entity_form_display.paragraph.media_gallery.default.yml
- config/install/core.entity_view_display.block_content.media_gallery.default.yml
- config/install/core.entity_view_display.paragraph.media_gallery.default.yml
- config/install/field.field.block_content.media_gallery.field_gallery_featured_image.yml
- config/install/field.field.block_content.media_gallery.field_gallery_media.yml
- config/install/field.field.block_content.media_gallery.field_tags.yml
- config/install/field.field.block_content.media_gallery.field_topic.yml
- config/install/field.field.node.landing_page.field_landing_page_component.yml
- config/install/field.field.paragraph.media_gallery.field_paragraph_media_gallery.yml
- config/install/field.storage.block_content.field_gallery_featured_image.yml
- config/install/field.storage.block_content.field_gallery_media.yml
- config/install/field.storage.paragraph.field_paragraph_media_gallery.yml
- config/install/paragraphs.paragraphs_type.media_gallery.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.block_content--media_gallery.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--media_gallery.yml
- tests/behat/features/fields.feature
- tide_landing_page.info.yml
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-94
> [SDPA-94] Added Image Gallery.

- composer.json
- config/install/core.entity_form_display.paragraph.card_event.default.yml
- config/install/core.entity_view_display.paragraph.card_event.default.yml
- config/install/field.field.paragraph.card_event.field_paragraph_date_range.yml
- tide_landing_page.info.yml
Jira Story: https://digital-engagement.atlassian.net/browse/SDPA-970
CONTENT PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/269
Tide Event PR: https://github.com/dpc-sdp/tide_event/pull/11
Force tide_core to release 0.0.3 due Bug: https://digital-engagement.atlassian.net/browse/SDPA-1008
**Changes**
1. Added data range field to card event manual
**Screenshots**
> [SDPA-970] Add date range date field to card event (manual) paragraph

- config/install/core.entity_form_display.paragraph.latest_events.default.yml
- config/install/core.entity_view_display.paragraph.latest_events.default.yml
- config/install/field.field.node.landing_page.field_landing_page_component.yml
- config/install/field.field.paragraph.latest_events.field_paragraph_cta_card_event.yml
- config/install/field.field.paragraph.latest_events.field_paragraph_title.yml
- config/install/field.storage.paragraph.field_paragraph_cta_card_event.yml
- config/install/paragraphs.paragraphs_type.latest_events.yml
- tests/behat/features/fields.feature
- tide_landing_page.info.yml
Jira Story: https://digital-engagement.atlassian.net/browse/SDPA-916
CONTENT PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/274
**Changes**
1. Add paragraph Latest news
2. Add Latest news paragraph to body content
**Screenshots**
> [SDPA-916] Add latest events paragraph to Body contents

- config/install/core.entity_form_display.paragraph.card_carousel.default.yml
- config/install/core.entity_view_display.paragraph.card_carousel.default.yml
- config/install/field.field.node.landing_page.field_landing_page_component.yml
- config/install/field.field.paragraph.card_carousel.field_paragraph_items.yml
- config/install/field.field.paragraph.card_carousel.field_paragraph_latest_items.yml
- config/install/field.field.paragraph.card_carousel.field_paragraph_title.yml
- config/install/field.storage.paragraph.field_paragraph_items.yml
- config/install/field.storage.paragraph.field_paragraph_latest_items.yml
- config/install/paragraphs.paragraphs_type.card_carousel.yml
- tests/behat/features/fields.feature
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-855
**Related PRs**
`content-vic`: dpc-sdp/content-vic-gov-au#283
1.  Added the Card Carousel component.
> [SDPA-855] Added Card Carousel paragraph.

- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--introduction_banner.yml
- tide_landing_page.info.yml
- https://digital-engagement.atlassian.net/browse/SDPA-1060
Content PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/304
Nuxt PR for QA: https://github.com/dpc-sdp/vic-gov-au/pull/291
1. Add JSON API enhancer for `field_paragraph_links`, used in Landing page -> Header Content tab -> Introduction Banner component.
> [SDPA-1060] Added API enhancers for field_paragraph_links.

- config/install/core.entity_form_display.paragraph.card_event.default.yml
- config/install/core.entity_view_display.paragraph.card_event.default.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1154
Content PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/325
1.  Remove date field from card event paragraph
> [SDPA-1154] Remove date field from card event

- config/install/field.field.node.landing_page.field_landing_page_component.yml
- config/install/paragraphs.paragraphs_type.timelines.yml
- tests/behat/features/fields.feature
- tide_landing_page.info.yml
Story: https://digital-engagement.atlassian.net/browse/SDPA-741
- Added changed configuration that allows Timeline paragraph types to be referenced in landing page components.
> [SDPA-741] Added Timelines to the list of allowed components.

- config/install/core.entity_form_display.paragraph.contact_us.default.yml
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-537
RELATED PRs:
1. Content PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/408
**Changes**
1. Update social media paragraph form display in contact us paragraph
> [SDPA-537] Update social media paragraph form display in contact us paragraph

- config/install/field.field.paragraph.hero_banner_with_cta.field_paragraph_cta.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1539
Tide Content PR : https://github.com/dpc-sdp/content-vic-gov-au/pull/417
1. Force link text required if URL is provided
> [SDPA-1539] Force link text required if URL is provided

- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--banner.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--basic_text.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--call_to_action.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--card_event.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--card_keydates.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--card_navigation.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--card_navigation_auto.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--card_navigation_featured.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--card_navigation_featured_auto.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--card_promotion.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--card_promotion_auto.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--contact_us.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--embedded_webform.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--featured_news.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--key_journeys.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--keydates.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--phone.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--social_link.yml
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-2192
> Reverted entity_id aliasing in favour of JSON:API 2.x.

- config/install/field.field.paragraph.social_link.field_paragraph_link.yml
- tide_landing_page.install
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1617
- Content BE: https://github.com/dpc-sdp/content-vic-gov-au/pull/543
1.  Make social link fields required fields.
> [SDPA-1617] Make social link fields required.

- config/install/core.entity_form_display.paragraph.complex_image.default.yml
- config/install/core.entity_view_display.paragraph.complex_image.default.yml
- config/install/field.field.node.landing_page.field_landing_page_component.yml
- config/install/field.field.paragraph.complex_image.field_complex_image_caption.yml
- config/install/field.field.paragraph.complex_image.field_complex_image_data.yml
- config/install/field.field.paragraph.complex_image.field_complex_image_dl_label.yml
- config/install/field.field.paragraph.complex_image.field_complex_image_full_label.yml
- config/install/field.field.paragraph.complex_image.field_complex_image_media.yml
- config/install/field.field.paragraph.complex_image.field_complex_image_source.yml
- config/install/field.field.paragraph.complex_image.field_complex_image_title.yml
- config/install/field.storage.paragraph.field_complex_image_caption.yml
- config/install/field.storage.paragraph.field_complex_image_data.yml
- config/install/field.storage.paragraph.field_complex_image_dl_label.yml
- config/install/field.storage.paragraph.field_complex_image_full_label.yml
- config/install/field.storage.paragraph.field_complex_image_media.yml
- config/install/field.storage.paragraph.field_complex_image_source.yml
- config/install/field.storage.paragraph.field_complex_image_title.yml
- config/install/paragraphs.paragraphs_type.complex_image.yml
- tests/behat/features/fields.feature
- tide_landing_page.info.yml
- tide_landing_page.install
https://digital-engagement.atlassian.net/browse/SDPA-2416
> Added Complex Image component.

- tide_landing_page.install
> Fixed update hook to remove complex image caption.

- config/install/core.entity_form_display.node.landing_page.default.yml
- config/install/core.entity_view_display.node.landing_page.default.yml
- config/install/field.field.node.landing_page.field_show_hero_image_caption.yml
- config/install/field.storage.node.field_show_hero_image_caption.yml
- tide_landing_page.info.yml
- tide_landing_page.install
- tide_landing_page.module
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-3038
> Added Show Hero Image caption field.

- config/install/core.entity_form_display.node.landing_page.default.yml
- config/install/field.field.node.landing_page.field_show_c_primary_caption.yml
- config/install/field.storage.node.field_show_c_primary_caption.yml
- tide_landing_page.info.yml
- tide_landing_page.install
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-3049
> Added Show Primary Campaign caption field.

- config/install/field.storage.paragraph.field_paragraph_social_list.yml
- tide_landing_page.install
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3735
1.  Added youtube to the socila media list paragraph field.
> [SDPA-3735] Added youtube to social media list.

- composer.json
- config/install/core.entity_form_display.paragraph.embedded_search_form.default.yml
- config/install/core.entity_view_display.paragraph.embedded_search_form.default.yml
- config/install/field.field.paragraph.embedded_search_form.field_paragraph_search_ph.yml
- config/install/field.field.paragraph.embedded_search_form.field_paragraph_search_target.yml
- config/install/field.field.paragraph.embedded_search_form.field_paragraph_search_url.yml
- config/install/field.storage.paragraph.field_paragraph_search_block.yml
- config/install/field.storage.paragraph.field_paragraph_search_ph.yml
- config/install/field.storage.paragraph.field_paragraph_search_target.yml
- config/install/field.storage.paragraph.field_paragraph_search_url.yml
- dev-tools.sh
- tide_landing_page.info.yml
- tide_landing_page.install
- tide_landing_page.module
> Added Custom to Embedded Search form.

- config/install/core.entity_form_display.paragraph.card_promotion_auto.default.yml
- config/install/core.entity_view_display.paragraph.card_promotion_auto.default.yml
- config/install/field.field.paragraph.card_promotion_auto.field_paragraph_display_topic.yml
- config/install/field.storage.paragraph.field_paragraph_display_topic.yml
- tide_landing_page.info.yml
- tide_landing_page.install
Added topic toggle for promo card auto.
> [SDPA-3945] Added topic toggle for promo card auto

- composer.json
- config/install/field.field.paragraph.call_to_action.field_paragraph_body.yml
- tide_landing_page.install
https://digital-engagement.atlassian.net/browse/SDPA-3993
1. change `rich_text` to `0` in `ThirdPartySetting`.
Updates Call to action component to enable WYSIWYG.
> SDPA-3993 Updates Call to action component

- tide_landing_page.install
https://digital-engagement.atlassian.net/browse/SDPSUP-1832
1. Added hook dependencies.
https://github.com/dpc-sdp/tide_core/pull/154
https://github.com/dpc-sdp/tide_site/pull/57
> [SDPSUP-1832] Added hook dependencies.

- composer.json
- config/install/core.entity_view_display.node.landing_page.default.yml
- dev-tools.sh
- tide_landing_page.install
https://digital-engagement.atlassian.net/browse/SDPA-4193
> [SDPA-4193] moves intro_text to top

- config/install/core.entity_form_display.paragraph.media_gallery.default.yml
- config/install/field.field.paragraph.media_gallery.field_paragraph_media_gallery.yml
- tide_landing_page.install
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4449
- Content: https://github.com/dpc-sdp/content-vic-gov-au/pull/930
1.  Add placeholder and helper text to Image gallery field
> [SDPA-4449] Add placeholder and helper text to Image Gallery

- config/install/core.entity_form_display.paragraph.keydates.default.yml
- config/install/field.field.paragraph.keydates.field_paragraph_keydate.yml
- js/hide_elements.js
- tide_landing_page.install
- tide_landing_page.libraries.yml
- tide_landing_page.module
https://digital-engagement.atlassian.net/browse/SDPA-4451
1. Retain Key dates heading at top of component but remove two additional ones between
- before
- after
2. Change first field label 'Key dates' to 'Date'
3. Remove the fields 'URL' and 'Link text'
4. Change button label from 'Add Keydates' to 'Add another date'
5. Remove 'CTA' heading and change field labels as follows: 
6. 'URL' changed to 'CTA link'
7. 'Link text' to 'CTA text'
8. The help text , more detail see https://digital-engagement.atlassian.net/browse/SDPA-4451
https://github.com/dpc-sdp/content-vic-gov-au/pull/933
> [SDPA-4451]CMS UI improvement - paragraph labels

- config/install/core.entity_form_display.paragraph.form_embed_openforms.default.yml
- config/install/core.entity_view_display.paragraph.form_embed_openforms.default.yml
- config/install/field.field.node.landing_page.field_landing_page_component.yml
- config/install/field.field.paragraph.form_embed_openforms.field_form_link.yml
- config/install/field.storage.paragraph.field_form_link.yml
- config/install/paragraphs.paragraphs_type.embedded_webform.yml
- config/install/paragraphs.paragraphs_type.form_embed_openforms.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--form_embed_openforms.yml
- tests/behat/features/fields.feature
- tide_landing_page.info.yml
- tide_landing_page.install
https://github.com/dpc-sdp/tide_landing_page/pull/103#discussion_r480464496
1. move the deletion of field_paragraph_summary to a new update hook.
> Fixes an error in 8025 hook update

- tide_landing_page.module
https://digital-engagement.atlassian.net/browse/SDPA-4632
1. Added check to set default value if not set.
> [SDPA-4632] Added check to set default value if not set.

- tide_landing_page.module
https://digital-engagement.atlassian.net/browse/SDPA-4885
https://github.com/dpc-sdp/tide_core/pull/201
https://github.com/dpc-sdp/tide_webform/pull/47
> [SDPA-4885] Fixes node clone layout issue

- src/Plugin/jsonapi/FieldEnhancer/CardLinkEnhancer.php
https://digital-engagement.atlassian.net/browse/SW-763
1. Updated card enhancer to check for empty nodes and empty topics and tags.
> [SW-763] Updated card link enhancer.

- src/Plugin/jsonapi/FieldEnhancer/CardLinkEnhancer.php
Updated function to be nonstatic as it will not be used somewhere else.
> [static-function] Updated getImage function.

- tide_landing_page.install
- tide_landing_page.post_update.php
https://digital-engagement.atlassian.net/browse/SW-786
1. fixes known issues
2. excludes `call_to_action`
> [SW-786] Fixes known issues and excludes `call_to_action`

- src/Plugin/jsonapi/FieldEnhancer/CardLinkEnhancer.php
- tide_landing_page.api.php
- tide_landing_page.install
https://digital-engagement.atlassian.net/browse/SW-827
1. Updated enhancer to add the PID in the JSON, which will be used in tide_site to handle the URLs that belong to other sites.
https://github.com/dpc-sdp/tide_site/pull/82
> [SW-827] Added parent node id.

- config/install/paragraphs.paragraphs_type.news_listing.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/DDS-823
**JIRA issue:** https://digital-engagement.atlassian.net/browse/DDS-809
1.  Add a missing component yml for installation.
> Add missing news_listing config

- .circleci/config.yml
- composer.json
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--basic_text.yml
- dev-tools.sh
- src/Plugin/jsonapi/FieldEnhancer/BasicTextEnhancer.php
- tests/unit/UnicodeWhitespaceTest.php
- tide_landing_page.install
https://digital-engagement.atlassian.net/browse/SDPA-5895
Parent ticket - https://digital-engagement.atlassian.net/browse/SDPA-5756
Added an enhancer for basic text, which will check the pasted content from the user and strip out any unicode uneven spacing character before sending it through JSON API.
Content-vic test branch - 
https://github.com/dpc-sdp/content-vic-gov-au/pull/1302
> Added basic text enhancer.

- js/statistics_grid.js
- tide_landing_page.libraries.yml
**Jira** : https://digital-engagement.atlassian.net/browse/SDPA-6057
Changes
1) Fix incorrect number of statistic grid blocks during edit after deleting a stat grid block
> [SDPA-6057] Fix Statistics Grid Edit incorrect number of grids

- config/install/field.field.node.landing_page.field_show_content_rating.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-6122
1.  Renamed label and descriptions.
Reference site didn't pick up this https://github.com/dpc-sdp/tide_landing_page/pull/124/commits/1a0e873601ae8097bde59d827bc50d0e80427272#diff-834c23a3d3bb3025e02096ffd669ad84f6ebc324de830af34356dd929229134fR11 until now. 
Before
After
> [SDPA-6122 content rating replaced by a related content

- config/install/core.entity_form_display.paragraph.statistics_grid.default.yml
- tide_landing_page.install
**JIRA** - https://digital-engagement.atlassian.net/browse/SDPA-6050
Changed
1) Add statistic_grid default value to config
2) Add update hook to set default value to 2
> [SDPA-6050] Fix stat grid default 2 blocks not showing

- config/install/field.field.paragraph.media_gallery.field_paragraph_media_gallery.yml
- tide_landing_page.install
**Jira** : https://digital-engagement.atlassian.net/browse/SDPA-6199
Changes
1. Image gallery CMS help link " [how to create an image gallery](https://www.singledigitalpresence.vic.gov.au/create-image-gallery)" to open in a new window instead the same window.
> [SDPA-6199] Image gallery CMS help link to open in new window

- dev-tools.sh
- tide_landing_page.install
https://digital-vic.atlassian.net/browse/SDPAP-6345
the update was added in wrong update hook and didn't get run in the previous release.
Added a new hook to run the updates
Devops ticket raised to fix it - https://digital-vic.atlassian.net/browse/DDS-1263
> [SDPAP-6345] help links opening in new tab

- config/install/field.field.node.landing_page.field_node_display_headings.yml
- config/install/field.field.node.landing_page.field_show_table_of_content.yml
- dev-tools.sh
- tests/behat/features/fields.feature
https://digital-vic.atlassian.net/browse/SDPAP-6287
Updated field_node_display_headings and field_show_table_of_content configs install.
https://github.com/dpc-sdp/tide_core/pull/333
> [SDPAP-6365] update table of contents and display headings

- config/install/field.field.paragraph.promotion_card.field_promo_card_display_style.yml
- tide_landing_page.install
https://digital-vic.atlassian.net/browse/SDPAP-5944
1. Update default image style at promotion_card to noImage value
> SDPAP-5944: Set default value to noImage on promotion card.

- composer.json
- config/install/field.storage.paragraph.field_paragraph_social_list.yml
- tide_landing_page.install
https://digital-vic.atlassian.net/browse/SDPAP-7642
Add new value "Website" to social media option.
Set allowed to unlimited
**api**
> [SDPAP-7642] KYC contact us new social list value.

- config/install/core.entity_form_display.paragraph.statistics_grid.default.yml
- tide_landing_page.install
https://digital-vic.atlassian.net/browse/SDPAP-7621
change the widget from `Paragraphs Legacy` to `Paragraphs (stable)` as  `Paragraphs Legacy` is incompatible with our needs.
> [SDPAP-7621] Update widget for Statistics Grid

- config/install/core.entity_form_display.node.landing_page.default.yml
- config/install/field.field.node.landing_page.field_content_category.yml
- tide_landing_page.install
https://digital-vic.atlassian.net/browse/SDPAP-8421
- https://github.com/dpc-sdp/tide_core/pull/450
> [SDPAP-8421] Apply content category field and taxonomy

- config/install/field.storage.paragraph.field_paragraph_search_block.yml
- tide_landing_page.install
Reverting work for this ticket https://digital-vic.atlassian.net/browse/SDPAP-8672
> revert changes

- src/Helper/TideLandingPageHelper.php
https://digital-vic.atlassian.net/browse/SDPAP-9438
> Landing page is displayed with promo card  and date of news article is displayed as a range with end date being current date
> [SDPAP-9438] Fix date display issue for Promo cards
