dpc-sdp/tide_landing_page

config/install/core.entity_form_display.node.landing_page.default.yml, config/install/core.entity_view_display.node.landing_page.default.yml, config/install/field.field.node.landing_page.field_landing_page_c_primary.yml, config/install/field.field.node.landing_page.field_landing_page_c_secondary.yml
JIRA:
- https://digital-engagement.atlassian.net/browse/SDPA-966
Changes:
1. Change `entity_reference_revisions_autocomplete` to `entity_reference_autocomplete` in form display
2. Correct type in view mode. Note we only need the `entity_reference_entity_id` instead of `entity_reference_entity_view` since the landing page content type only need to reference the campaign entity_id
**Note**: this PR also have the changes in https://github.com/dpc-sdp/tide_landing_page/pull/23
=> [SDPA-966] Updated campaign field config for landing page module

config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--card_event.yml
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-1354
RELATED PRs:
1. Content PR:  https://github.com/dpc-sdp/content-vic-gov-au/pull/363
**Changes**
1. Add enhancer for field_paragraph_date_range
=> [SDPA-1354] Manual Card Event - incorrect date shown if the date that is selected is in AM 

config/install/core.entity_form_display.paragraph.card_event.default.yml, tide_landing_page.install
more details see https://digital-engagement.atlassian.net/projects/SDPA/issues/SDPA-1225
relates to https://github.com/dpc-sdp/tide_landing_page/pull/73  close #73 because of a patch issue.
the update id was 8008(in the first commit in #73 `3d160044cc4ca2f788331c889d8bb2a02b2f837f`) which conflicts with an existing one.  there is no chance to amend the older commit to 8009. even though the latest commit is already 8009(in #73), which still causes a composer issue when updating with content-vic. 
created a new pr to avoid this issue.
=> [SDPA-1225] Tide - Summary field in carousal Card event is not ristricted to 200 characters

config/install/field.field.node.landing_page.field_landing_page_component.yml, tide_landing_page.install
Timeline paragraph should be available independently of tide_grant
https://digital-engagement.atlassian.net/browse/SDPA-3231
1. issue
As an editor I can add a timeline component to landing pages
2. Test Scenario
Without the Tide Grant module enabledAs a user with the editor role
3. Expected behaviour
When adding a landing page I can select Timeline from the list of body components
4. Actual behaviour
Timeline is not available
5. Solution direction
Move timeline config into tide_landing_page
Add update hook to install timeline component if not already installed
related PRs:
https://github.com/dpc-sdp/content-vic-gov-au/pull/708
https://github.com/dpc-sdp/tide_core/pull/95
=> [SDPA-3231] Fixed timelines missed issue

tide_landing_page.install
Parent ticket - https://digital-engagement.atlassian.net/browse/SDPA-4313
Sub task - https://digital-engagement.atlassian.net/browse/SDPA-4364
1. Added update hook to enable schedule transitions for tide_landing_page.
=> [SDPA-4364] Added update hook to enable landing page for use with scheduled transitions.

config/install/field.field.node.landing_page.field_landing_page_component.yml, tide_landing_page.install
https://digital-engagement.atlassian.net/browse/SDPA-4397
we found an issue with `field_landing_page_component`. in its `handler_settings`, `target_bundles_drag_drop` with `TRUE` doesn't match `target_bundles` vice versa. we would like to fix the issue.
1. adds an update hook to fix the issue described above.
=> [SDPA-4397] field_landing_page_component's handler_settings issue

tide_landing_page.module
https://digital-engagement.atlassian.net/browse/SDPA-4696
if the field `field_node_display_headings` and `field_show_table_of_content` both applied to a node form, the `#states` should also apply to.
move the logic out of `node_landing_page_form`
=> [SDPA-4696] apply the states api to all node form

tide_landing_page.install, tide_landing_page.post_update.php
The running of [tide_landing_page_update_8035(&$sandbox)](https://github.com/dpc-sdp/tide_landing_page/pull/134/files#diff-7e6f6816fd76f77a0b74239e31ba4e5b1e332854d8e55ceae374edfe98dfe08bR1367) `update hook` for `[content-vic]` project takes about 2 hours, which may broke the build, therefore, after had discussion with @nicksantamaria and @GROwen ,  we would like to run this hook only in `production`(or prod-left) environment 
1. check if `TIDE_LANDING_PAGE_RUN_8035` env variable exists, if it does , run the `tide_landing_page_update_8035()` update hook
2. change `str_contains()` to use `strpos()`.
=> Runs update_35 only on a production (or prod-left) environment

src/Access/BlockAccessCheck.php, src/Routing/RouteSubscriber.php, tests/behat/features/access_block.feature, tide_landing_page.links.menu.yml, tide_landing_page.services.yml
**JIRA issue:**
https://digital-engagement.atlassian.net/browse/SDPA-5058
**Changed**
Added new access checks
Added new event subscriber
Add custom menu item (Custom block library) under structure to allow users to create/manage blocks.
**Logic explanation**
- We need to restrict access the block layout for Approver/Site-Admin/Editor users and have a menu item visible for them to create/manage blocks.
- This won't arbitrary block/unblock all users access as it is specific for the roles requested on the ticket. Also, won't affect any other permissions.
- As a solution a custom menu item under structure have been added in order to allow Approver/Site-Admin/Editor users to create/manage blocks.
- Administrator role will be able to see this new custom menu item under structure. The fact of …
=> [SDPA-5058] Restrict block layout to administrators

config/install/field.field.node.landing_page.field_landing_page_component.yml, tide_landing_page.install
The component sequence was fixed only for content-vic and the weight wasn't updated in this module. 
Updated the component sequence matching Duncan's comment from the ticket and copying the weight from content-vic, so the sequence of components that belongs to tide_ladning_page stays the same for all projects.
=> [component-weight] Updated hook to get the new component weight and set it to sync config.

tide_landing_page.info.yml
Fix the fatal error when installing the module:
```
Drupal\Core\Config\UnmetDependenciesException: Configuration objects     [error]
provided by <em class="placeholder">tide_landing_page</em> have unmet
dependencies: <em
class="placeholder">core.entity_form_display.paragraph.data_table.default
(tablefield)</em> in
/app/docroot/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98
```
=> Added missing dependency tablefield.

tide_landing_page.module
https://digital-engagement.atlassian.net/browse/SDPA-5105
if the promotion and navigation card has an internal link referenced in it and when the internal link node gets updated, the details does not get updated in the cards where the node is referenced.
1. Added a function to query the nodes that are referencing a particual node in the promotion and navigation card.
2. Added node pre-save hook to clear cache for all the parent nodes where the current node is referred.
FE test link - https://app.pr-864.vic-gov-au.sdp2.sdp.vic.gov.au/
BE test link - https://nginx-php.pr-1172.content-vic.sdp2.sdp.vic.gov.au/
=> [SDPA-5105] Added hook to clear reference node cahce on presave.

tide_landing_page.module
https://digital-engagement.atlassian.net/browse/SDPA-5332
This is really an uncommon issue. There is a page in vicpol BE named careers and at some point the field_landing_page_component had 2 components in it. One of them got removed, but the delta element somehow didn't get updated and the delta element still points it has 2 components in it.
For this reason in `tide_landing_page_field_widget_paragraphs_form_alter` hook here `$paragraph = $widget_state['paragraphs'][$element['#delta']]['entity'];` the value of #delta gives 0 and 1 value. When it tries to get the paragraph for value 1 it returns null. Because of that this throws error on calling function on null `$paragraph->bundle();`
Rather than fix these kinds of issue using db query, I think best to put a check for empty paragraph and …
=> [SDPA-5332] Added paragraph bundle issue fix.

src/Plugin/jsonapi/FieldEnhancer/CardLinkEnhancer.php
https://digital-engagement.atlassian.net/browse/SDPA-5406
The card link enhancer sends out the empty summary for the news content type cause the summary field that was attached to the body field for the news content type does not exist anymore.
1. As the summary field that is attached to the body field for news content type is redundant now, this needs to be updated in the card link enhancer so that it doesn't have to look for the news content type-specific summary field anymore.
FE test link - https://app.pr-1012.ripple.sdp2.sdp.vic.gov.au/
BE test link - https://nginx-php.pr-1174.content-vic.sdp2.sdp.vic.gov.au/
=> [SDPA-5406] Removed reduandant summary field for tide_news module.

css/landing_page.css
**Jira** : https://digital-engagement.atlassian.net/browse/SDPA-6056
Changes
1) Please wait ajax progress under Confirm Removal Dropdown css changes to prevent overlapping of "Confirm Removal" text and "Please wait..."
=> [SDPA-6056] Fix Spinner overlapping in confirm removal dropdown

.circleci/config.yml
https://digital-vic.atlassian.net/browse/SRM-526
Ignoring build suggest to be run on reference branch in circle ci. As reference branch is a mirror copy of develop, it does not require the build suggest to run. If we want to run the build suggest it will require more maintenance work on the merge to reference script and it is not necessary to be tested against reference, so ignoring this should be fine.
=> Updated circle ci config.

tide_landing_page.install
Looping through all the paragraph ids wasn't a good idea. hook breaks with php memory error during build.
Run the hook only if any id exists with the type featured_news in batches.
=> Updated the hook to use batches when deleting depricated paragraph items.

tide_landing_page.module
https://digital-vic.atlassian.net/browse/SDPAP-8094
replaces `hook_field_widget_WIDGET_TYPE_form_alter` by `hook_field_widget_single_element_WIDGET_TYPE_form_alter`
https://www.drupal.org/node/3180429
> hook_field_widget_form_alter (hook_field_widget_WIDGET_TYPE_form_alter) was marked as deprecated and will be replaced by hook_field_widget_single_element_form_alter (hook_field_widget_single_element_WIDGET_TYPE_form_alter).
It seems that hook_field_widget_WIDGET_TYPE_form_alter is not functioning properly in Drupal 9.5.x due to the deprecation of functions.
=> [SDPAP-8094] Replacement of the deprecated function

src/Plugin/jsonapi/FieldEnhancer/CardLinkEnhancer.php
https://digital-vic.atlassian.net/browse/SRM-1237
The date field value accessing structure changed from `$node->get('field_publication_date')->getValue()[0]` to `$node->get('field_publication_date')->getValue()[0]['value']`, which causes throwing error for car enhancer when trying to send out api response for a page which has the publication page added in a card.
Matched the structure to access the single value for the field as this is not a range and only has one value.
=> [SRM-1237] Updated card enhancer to correctly access the date string value and pass it to the date converter.

config/install/field.storage.paragraph.field_paragraph_search_block.yml, tide_landing_page.install
https://digital-vic.atlassian.net/browse/SDPAP-8672
Remove news and event values from search block
Testing link: https://nginx-php.pr-379.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
=> [SDPAP-8672]remove news and event from search block
